name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      runmacOS: sudo xcode-select -switch /Applications/Xcode_14.2.app
      runiOS: sudo xcode-select -switch /Applications/Xcode_14.2.app

    - name: Build and test
      runmacOS: xcodebuild clean build test -project Weight.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
      runiOS: xcodebuild clean build test -project Weight.xcodeproj -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro" ONLY_ACTIVE_ARCH=YES
